name: deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: ${{ env.PROJECT_ID }}
          EMAIL_SENDER: ${{ env.EMAIL_SENDER }}
          EMAIL_RECIPIENT: ${{ env.EMAIL_RECIPIENT }}